# Generated by Django 2.1.4 on 2019-04-18 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tip', '0003_auto_20190418_1903'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tip',
            table='tip',
        ),
    ]
